# Browser Settings
browser=chrome
headless=false

# Wait Timeouts
implicit.wait=10
explicit.wait=30

filter.name=TC_RG_
excel.name=we1_superAdmin_regression.xlsx

#Test to run for super admin side add sheet name from this list below to sheets.name to run that sheet:
#---------------------------------------------------------------------------------------------------------
#SuperAdminLogin,AddCustomer,AddCityArea,AddCityAdmin,AddAutoDriver,AddBikeDriver,AddTaxiDriver,
# TransportServiceCompleteTest,AddTransportCityAdmin,TransportServiceStatisticsTest,TransportDriverStatisticsTest,
# TransportServiceRidesTest,TransportServiceAerialView,TransportServiceEarningReports,TransportProviderLists,
# TransportServiceReview,SubscriptionPlanTest,GeoFencingTest,PanicCallTest,DashboardTest,ReportIssueFaqs,CustomerReportIssues,
# AddStore,StoreOperations,StoreStatusManagement,DeliveryServiceCompleteTest,AddProvider,ProviderServiceCompleteTest,DataCleanUpSheet


sheets.name=SuperAdminLogin,AddCustomer,AddCityArea,AddCityAdmin,AddAutoDriver,AddBikeDriver,AddTaxiDriver,\
  TransportServiceCompleteTest,AddTransportCityAdmin,TransportServiceStatisticsTest,TransportDriverStatisticsTest,\
  TransportServiceRidesTest,TransportServiceAerialView,TransportServiceEarningReports,TransportProviderLists,\
  TransportServiceReview,SubscriptionPlanTest,GeoFencingTest,PanicCallTest,DashboardTest,ReportIssueFaqs,\
  CustomerReportIssues,DriverReportIssues,AddStore,StoreOperations,StoreStatusManagement,DeliveryServiceCompleteTest,\
  AddProvider,ProviderServiceCompleteTest
