# ==========================================
# CORE REGRESSION TEST DATA CREATED ON DATA BASE
# ==========================================
regression.approved_driver.phone=8494893566
regression.approved_driver.name=regression approved driver
regression.customer.phone=8529637418
regression.customer.name=regression customer
regression.subscription.approved_driver.phone=8998454522
regression.subscription.approved_driver.name=subscribe_regression_approve_driver
