# ==============================================================================
# ? WEB PLATFORM CONSOLE: SUPER ADMIN SETTING MODULE LOCATORS
# ==============================================================================

# Module Entry & Root Sidebar Controls
admin.setting.sidebar.menu=//h2[@id='Setting']


# Panic Call Module
admin.setting.panic_call.sidebar_menu=//span[@id='Panic Call']
admin.setting.panic_call.add_btn=//button[normalize-space()='Add Panic Calls']
admin.setting.panic_call.name_input=//input[@id='Name:']
admin.setting.panic_call.tamil_name_input=//input[@id='Name (Tamil):']
admin.setting.panic_call.hindi_name_input=//input[@id=' Name (Hindi):']
admin.setting.panic_call.contact_number=//input[@id='Contact Number:']
admin.setting.panic_call.status_dropdown=//div[@id='Panic Call Status:']
admin.setting.panic_call.activate_status_dropdown=//li[@aria-label='Activate']
admin.setting.panic_call.deactivate_status_dropdown=//li[@aria-label='Deactivate']
admin.setting.panic_call.search_name=//input[@aria-label='Name Filter Input']
admin.setting.panic_call.edit_btn=//i[@class='bi bi-pencil-square cursor-pointer gridIcon Edit']
admin.setting.panic_call.delete_btn=//i[@class='bi bi-trash cursor-pointer gridIcon Delete']
admin.setting.panic_call.confirm_delete_btn=//button[normalize-space()='Yes, delete it!']

# site setting Module
admin.setting.site_setting.sidebar_menu=//span[@id='Site Settings']
admin.setting.site_setting.wallet_dropdown=//div[@id='Wallet']
admin.setting.site_setting.walletdropdown_option_on=//li[@aria-label='on']
admin.setting.site_setting.walletdropdown_option_off=//li[@aria-label='off']
admin.setting.site_setting.Auto_Settle_dropdown=//div[@id='Auto Settle Module']
admin.setting.site_setting.Auto_Settle_option_on=//li[@aria-label='on']
admin.setting.site_setting.Auto_Settle_option_off=//li[@aria-label='off']

# Geo Fencing Module
admin.setting.geo_fencing.sidebar_menu=//span[@id='Geo Fencing']
admin.setting.geo_fencing.add_restricted_area_btn=//button[normalize-space()='Add Restrcited Area']
admin.setting.geo_fencing.area_name_input_field=//input[@id='Restricted Area Name']
admin.setting.geo_fencing.status_toggle_button=//label[contains(@class,'cursor-pointer')]
admin.setting.geo_fencing.form_submit_button=//button[normalize-space()='Submit']
admin.setting.geo_fencing.area_search_filter=//input[@aria-label='AREA Filter Input']
admin.setting.geo_fencing.edit_button=//i[@title='Edit']
admin.setting.geo_fencing.delete_button=//i[@title='Delete']
admin.setting.geo_fencing.confirm_delete_button=//button[normalize-space()='Yes, delete it!']


#Settings_site_setting

admin.global.form.dropdown_google_login=//div[@id='Google Login']
admin.global.form.dropdown_facebook_login=//div[@id='Facebook Login']
admin.global.form.dropdown_apple_login=//div[@id='Apple Login']
admin.settings.input_expiry_warning_first=//input[@id='Document Expiry Warning (First)']
admin.settings.input_expiry_warning_second=//input[@id='Document Expiry Warning (Second)']
admin.settings.input_expiry_warning_third=//input[@id='Document Expiry Warning (Third)']
admin.global.form.btn_clear_driver_subscription=//timesicon[@data-pc-section='clearicon']
web.global.transport_services.home_icon.earning_report=//button[normalize-space()='Earnings Reports']
web.global.Menu.admin_commission=//h2[@id='Admin Commission']
admin.orders.grid.input_filter_username=//input[@aria-label='User Name Filter Input']
web.gobal.Earing_report.tab_in_NO=//input[@aria-label='No Filter Input']
admin.earnings.grid.chk_first_row_selection=//div[@role='row' and .//div[text()='208']]//input[@type='checkbox']
web.gobal.Earing_report.mark_as_settle=//button[normalize-space()='Mark As Settle']


#Settings_site_setting
admin.settings.document.btn_trigger_change_algorithm=(//div[@id='Change Algorithm:']//chevrondownicon)[2]
admin.settings.document.btn_clear_change_algorithm=(//div[@id='Change Algorithm:']//timesicon[@data-pc-section='clearicon'])[2]
admin.settings.Driver_approval.btn_trigger_change_algorithm=(//div[@id='Change Algorithm:']//chevrondownicon)[1]
admin.settings.Driver_approval.btn_clear_change_algorithm=(//div[@id='Change Algorithm:']//timesicon[@data-pc-section='clearicon'])[1]
admin.global.form.btn_trigger_wallet=//div[@id='Wallet']//chevrondownicon
admin.global.form.btn_clear_wallet=//div[@id='Wallet']//timesicon[@data-pc-section='clearicon']
admin.global.form.btn_trigger_cash=//label[contains(.,'Cash')]/following-sibling::*//chevrondownicon
admin.global.form.btn_clear_cash=//div[@id='Cash']//timesicon[@data-pc-section='clearicon']
admin.global.form.btn_clear_provider_subscription=//div[@id='Driver Subscription']//timesicon[@data-pc-section='clearicon']
admin.global.form.dropdown_option_driver_subscription_on=//li[@id='Driver Subscription_0']/span[text()='on']
admin.global.form.btn_trigger_driver_subscription=//div[@id='Driver Subscription']//chevrondownicon
admin.settings.btn_trigger_google_login=//div[@id='Google Login']//chevrondownicon
admin.settings.btn_clear_google_login=//div[@id='Google Login']//timesicon[@data-pc-section='clearicon']
admin.settings.dropdown_calculation_method=//label[contains(.,'Calculation Method')]/following-sibling::*//chevrondownicon
admin.settings.btn_clear_calculation_method=//div[@id='Calculation Method']//timesicon[@data-pc-section='clearicon']
admin.settings.input_user_request_timeout=//input[@id='User Request Timeout(Seconds):']
admin.settings.dropdown_driver_algorithm=//div[@id='Driver Algorithm']//chevrondownicon
admin.settings.btn_clear_driver_algorithm=//div[contains(.,'Driver Algorithm')]//timesicon[@data-pc-section='clearicon']
admin.setting.site_settings.website_name=//input[@id='Website Name:']
admin.setting.site_settings.address=//textarea[@placeholder='Enter Address']
admin.setting.site_settings.edit_site_setting.admin_receive_email=//input[@id='Admin Receive Email:']
admin.setting.site_settings.edit_site_setting.email=//input[@id='Email:']
admin.setting.site_settings.edit_site_setting.contact_no=//input[@id='Contact No:']
admin.setting.site_settings.edit_site_setting.copy_right_content=//input[@id='Copy Right Content:']
admin.setting.site_settings.social_link.facebook_link=//input[@id='Facebook Link:']
admin.setting.site_settings.social_link.instagram_link=//input[@id='Instagram Link:']
admin.setting.site_settings.social_link.youtube_link=//input[@id='Youtube Link:']
admin.setting.site_settings.social_link.linkedin_link=//input[@id='Linkedin Link:']
admin.setting.site_settings.appstore_and_platstore_link.user_playstore_link=//input[@id='User Playstore Link:']
admin.setting.site_settings.appstore_and_platstore_link.user_appstore_link=//input[@id='User Appstore Link:']
admin.setting.site_settings.appstore_and_platstore_link.provider_playstore_link=//input[@id='Provider Playstore Link:']
admin.setting.site_settings.appstore_and_platstore_link.provider_appstore_link=//input[@id='Provider Appstore Link:']
admin.setting.site_settings.appstore_and_platstore_link.driverdelivery_playstore_link=//input[@id='Driver/Delivery Playstore Link:']
admin.setting.site_settings.appstore_and_platstore_link.driverdelivery_appstore_link=//input[@id='Driver/Delivery Appstore Link:']
admin.setting.site_settings.appstore_and_platstore_link.store_playstore_link=//input[@id='Store Playstore Link:']
admin.setting.site_settings.appstore_and_platstore_link.store_appstore_link=//input[@id='Store Appstore Link:']
admin.setting.site_settings.user_refer_discount.used_user_discount=//input[@id='Used User Discount:']
admin.setting.site_settings.user_refer_discount.used_user_discount_type.amount=//li[@role='option' and @aria-label='Amount']
admin.setting.site_settings.user_refer_discount.used_user_discount_type.percentage=//li[@role='option' and @aria-label='Percentage']
admin.setting.site_settings.user_refer_discount.refer_used_discount=//input[@id='Refer User Discount:']
admin.setting.site_settings.refer_user_discount_type.amount=//li[@role='option' and @aria-label='Amount']
admin.setting.site_settings.refer_user_discount_type.percentage=//li[@role='option' and @aria-label='Percentage']
admin.setting.site_settings.delivery_admin_commission.delivery_commission=//input[@id='Delivery Commision (in %):']
admin.setting.site_settings.ondemand_start_service_time=//input[@id='Provider can start the service before  minutes of requested time.']
admin.setting.site_settings.driver_algorithm.competitive_algorithm=//li[@id='Driver Algorithm_0']/span[text()='Competitive Algorithm']
admin.setting.site_settings.driver_algorithm.nearest_1st=//span[@aria-label='Nearest 1st']
admin.setting.site_settings.calculation_for_transport_service.calculation_method=//li[@id='Calculation Method_0']/span[text()='Find Distance/Eta using Google Map Distance Matrix Api']
admin.setting.site_settings.re_calculate_method_transport_service.estimated_calculation=//span[@aria-label='Estimated Calculation']
admin.setting.site_settings.re_calculate_method_transport_service.actual_calculation=//span[@aria-label='Re Calculate (Actual Calculation) at ride completion']
admin.setting.site_settings.social_login.google_login.on=//li[@aria-label='on']
admin.setting.site_settings.social_login.google_login.off=//li[@aria-label='off']
admin.setting.site_settings.social_login.facebook_login.on=//span[@aria-label='on']
admin.setting.site_settings.social_login.facebook_login.off=//span[@aria-label='off']
admin.setting.site_settings.social_login.apple_login.on=//span[@aria-label='on']
admin.setting.site_settings.social_login.apple_login.off=//span[@aria-label='off']
admin.setting.site_settings.document_expiry_warning_first=//input[@id='Document Expiry Warning (First)']
admin.setting.site_settings.document_expiry_warning_second=//input[@id='Document Expiry Warning (Second)']
admin.setting.site_settings.document_expiry_warning_third=//input[@id='Document Expiry Warning (Third)']
admin.setting.site_settings.driver_subscription.on=//span[@aria-label='on']
admin.setting.site_settings.driver_subscription.off=//span[@aria-label='off']
admin.setting.site_settings.store_subscription.on=//span[@aria-label='on']
admin.setting.site_settings.store_subscription.off=//span[@aria-label='off']
admin.setting.site_settings.provider_subscription.on=//span[@aria-label='on']
admin.setting.site_settings.provider_subscription.off=//span[@aria-label='off']
admin.setting.site_settings.user_subscription.on=//span[@aria-label='on']
admin.setting.site_settings.user_subscription.off=//span[@aria-label='off']
admin.setting.site_settings.toll_charge.off=//span[@aria-label='Off']
admin.setting.site_settings.toll_charge.final_toll_charge_given_by_driver=//span[@aria-label='Final Toll Charge given by driver']
admin.setting.site_settings.toll_charge.decided_by_Admin=//span[@aria-label='No. of Tolls given by Driver & Charge per Toll decided by Admin']
admin.setting.site_settings.payments_method.cash.on=//ul[@id='Cash_list']//li[@aria-label='on']//span[text()='on']
admin.setting.site_settings.payments_method.cash.off=//span[@aria-label='off']
admin.setting.site_settings.payment_method.razor_pay.on=//span[@aria-label='on']
admin.setting.site_settings.payment_method.razor_pay.off=//span[@aria-label='off']
admin.setting.site_settings.wallet.on=//li[@role='option'][normalize-space()='on']
admin.setting.site_settings.wallet.off=//li[@role='option'][normalize-space()='off']
admin.setting.site_settings.auto_settle_module.dropdown=//div[@id='Auto Settle Module']//span[@role='combobox']
admin.setting.site_settings.auto_settle_module.off=//ul[@id='Auto Settle Module_list']//li[@aria-label='off']
admin.setting.site_settings.minimum_wallet_amount_driver=//input[@id='Minimum Wallet Required Amount for Request(Driver)']
admin.setting.site_settings.minimum_wallet_amount_subscribe_driver=//input[@id='Minimum Wallet Required Amount for Request(Subscribe Driver)']
admin.setting.site_settings.minimum_wallet_amount_store=//input[@id='Minimum Wallet Required Amount for Request(Store)']
admin.setting.site_settings.minimum_wallet_amount_subscribe_store=//input[@id='Minimum Wallet Required Amount for Request(Subscribe Store)']
admin.setting.site_settings.minimum_wallet_amount_provider=//input[@id='Minimum Wallet Required Amount for Request(Provider)']
admin.setting.site_settings.minimum_wallet_amount_subscribe_provider=//input[@id='Minimum Wallet Required Amount for Request(Subscribe Provider)']
admin.setting.site_settings.minimum_cash_out_amount=//input[@id='Minimum Cash Out Amount:']
admin.setting.site_settings.maximum_cash_out_amount=//input[@id='Maximum Cash Out Amount:']
admin.setting.site_settings.re_assign=//input[@id='Max Re-assign Driver:']
admin.setting.site_settings.schedule_notification=//input[@id='Schedule Notification (in minutes):']
admin.setting.site_settings.account_auto_approvel=//span[@aria-label='Auto Approval']
admin.setting.site_settings.account_manual_approvel=(//ul[contains(@id, 'Change Algorithm')])[1]//li//span[normalize-space(text())='Manual Approval from Admin']
admin.setting.site_settings.document_auto_approvel=//span[@aria-label='Auto Approval']
admin.setting.site_settings.document_manual_approvel=(//ul[contains(@id, 'Change Algorithm')])[1]//li[@aria-label='Manual Approval from Admin']
admin.setting.site_settings.video_call_time=//input[@id='Video Call Time Limit Per Order']
admin.setting.site_settings.video_call_toggle=//div[contains(normalize-space(), 'Allow Daily Video Call Limit Per User')]/following-sibling::label
admin.setting.site_settings.daily_video_call_per_person=//input[@id='Daily Video Call Time Limit Per User']
admin.setting.site_settings.email_notification_on=
admin.setting.site_settings.email_notification_off=
admin.setting.site_settings.subscription_expiry_warning_first=//input[@id='Subscription Expiry Warning (First)']
admin.setting.site_settings.subscription_expiry_warning_second=//input[@id='Subscription Expiry Warning (Second)']
admin.settings.btn_submit=//button[text()=' Submit ']
admin.settings.document.btn_clear_email_notification=//div[@id='Email notification']//timesicon[@class='p-element p-icon-wrapper ng-star-inserted']//*[name()='svg']
admin.settings.document._email_notification_dropdown=//div[@id='Email notification']//chevrondownicon[@class='p-element p-icon-wrapper ng-star-inserted']//*[name()='svg']
admin.settings.document._email_notification_option_on=//li[@id='Email notification_1']

#setting_inccomplete_registration
admin.setting.incomplete_registration=//span[@id='Incomplete Registration']
admin.setting.incomplete_registration.email=//input[@id='ag-151-input']
admin.setting.incomplete_registration.gride_search_providers_type=//input[@id='ag-157-input']
admin.setting.incomplete_registration.delete_icon=(//i[@class='bi bi-trash cursor-pointer gridIcon Modify'])[1]
admin.setting.incomplete_registarion.delete_yes_button=//button[@class='swal2-confirm swal2-styled']


#push_notification
admin.setting.push_notification=//span[@id='Push Notification']
admin.setting.push_notification.add_push_notification=//button[normalize-space()='Add Push Notification']
admin.setting.push_notification.notification_type=//span[@aria-label='Select Notification Type']
admin.setting.push_notification.all_users=//ul[@id='Notification Type_list']//li[@aria-label='All Users']
admin.setting.push_notification.all_drivers=//li[@id='Notification Type_2']
admin.setting.push_notification.all_stores=//li[@id='Notification Type_3']
admin.setting.push_notification.all_providers=//li[@id='Notification Type_4']
admin.setting.push_notification.title=//input[@id='Title']
admin.setting.push_notification.message=//input[@id='Message']
admin.setting.push_notification.all_users_drivers_stores_providers=//span[@class='ng-star-inserted'][normalize-space()='All Users, Drivers, Stores And Providers']
admin.setting.push_notification.notification_field=//span[@aria-label='Select Notification Type']
admin.setting.push_notification.notification_all_users=//span[@class='ng-star-inserted'][normalize-space()='All Users']
admin.setting.push_notification.gride_search_notification=//input[@id='ag-9305-input']
admin.setting.push_notification.delete_cancel_button=//button[normalize-space()='Cancel']
admin.setting.push_notification.select_notification_type_all_users=//li[@id='Notification_1']
admin.setting.push_notification.select_notification_type_all_drivers=//li[@id='Notification_2']
admin.setting.push_notification.select_notification_type_all_stores=//li[@id='Notification_3']
admin.setting.push_notification.select_notification_type_all_providers=//li[@id='Notification_4']
admin.setting.push_notification.select_notification_type_all_users_drivers_stores_providers=//span[@class='ng-star-inserted'][normalize-space()='All Users, Drivers, Stores And Providers']
admin.setting.push_notification.title_gride_search=//input[@aria-label='Title Filter Input']


#World_Currency Module
admin.setting.world_currency.side_bar_menu=//span[@id='World Currency']
admin.setting.world_currency.heading=//div[normalize-space()='World Currency']
admin.setting.world_currency.search_bar=//input[@aria-label='Currency Name Filter Input']
admin.setting.world_currency.edit_button=//i[@class='bi bi-pencil-square cursor-pointer gridIcon Edit']
admin.setting.world_currency.ratio_input_box=//input[@id='Ratio']
admin.setting.world_currency.ratio_submit_button=//button[normalize-space()='Submit']
admin.setting.world_currency.success_pop_up=//div[@aria-label='Updated Successfully']

#App_Version_Setting_Module
admin.setting.app_version_setting.side_bar_menu=//span[@id='App Version Setting']
admin.setting.app_version_setting.heading=//div[normalize-space()='App Version Settings']
admin.setting.app_version_setting.app_type_search_bar=//input[@aria-label='App Type Filter Input']
admin.setting.app_version_setting.platform_search_bar=//input[@aria-label='Platform Filter Input']
admin.setting.app_version_setting.edit_button=//i[@class='bi bi-pencil-square cursor-pointer gridIcon Edit']
admin.setting.app_version_setting.version_name_input=//input[@id='Version Name']
admin.setting.app_version_setting.submit_button=//button[normalize-space()='Submit']
admin.setting.app_version_setting.success_pop_up=//div[@aria-label='Updated Successfully']

#Email Templates
admin.setting.email_templates.side_bar_menu=//span[@id='Email Templates']
admin.setting.email_templates.heading=//div[normalize-space()='Email Template List']
admin.setting.email_templates.title_search_bar=//input[@aria-label='TITLE Filter Input']
admin.setting.email_templates.edit_button=//i[@class='bi bi-pencil-square cursor-pointer gridIcon Edit']
admin.setting.email_templates.title_input=//input[@id='Title']
admin.setting.email_templates.submit_btn=//button[normalize-space()='Submit']
admin.setting.email_templates.success_pop_up=//div[@aria-label='Updated Successfully']

#Super Admin Profile Details
admin.setting.profile_Details.side_bar_menu=//span[@id='Profile Details']
admin.setting.profile_Details.heading=//h2[text()='Profile Details']
admin.setting.profile_Details.change_password=//button[normalize-space()='Change Password']
admin.setting.profile_Details.current_password_input=//input[@placeholder='Enter current password']
admin.setting.profile_Details.new_password_input=//input[@placeholder='Enter new password']
admin.setting.profile_Details.repeat_password_input=//input[@placeholder='Re-enter new password']
admin.setting.profile_Details.update_password_btn=//button[normalize-space()='Update Password']
admin.setting.profile_Details.cancel_password_btn=//button[normalize-space()='Cancel']
admin.setting.profile_Details.profile_edit_btn=//button[normalize-space()='Edit']
admin.setting.profile_Details.save_changes_btn=//button[normalize-space()='Save Changes']
admin.setting.profile_Details.cancel_btn=//button[normalize-space()='Cancel']