#customer_app_support
admin.page_list=//h2[@id='Page List']
admin.page_list.customer_app_support=//span[@id='Customer App Support']
admin.page_list.customer_app_support.contact_us=//button[normalize-space()='Contact Us']
admin.page_list.customer_app_support.disclaimer=//button[normalize-space()='Disclaimer']
admin.page_list.customer_app_support.privacy_policy=//button[normalize-space()='Privacy Policy']
admin.page_list.customer_app_support.terms_and_conditions=//button[normalize-space()='Terms And Conditions']
admin.page_list.customer_app_support.about_us=//button[normalize-space()='About Us']
admin.page_list.customer_app_support.faq=//button[normalize-space()='Faq']

#driver_app_support
admin.page_list.driver_app_support=//span[@id='Driver App Support']
admin.page_list.driver_app_support.contact_us=//button[normalize-space()='Contact Us']
admin.page_list.driver_app_support.faq=//button[normalize-space()='Faq']
admin.page_list.driver_app_support.disclaimer=//button[normalize-space()='Disclaimer']
admin.page_list.driver_app_support.privacy_policy=//button[normalize-space()='Privacy Policy']
admin.page_list.driver_app_support.Terms_and_conditions=//button[normalize-space()='Terms And Conditions']
admin.page_list.driver_app_support.about_us=//button[normalize-space()='About Us']

# COMMON LOCATORS
admin.page_list.common.name_arabic.input=//input[@id='Name(Arabic):']
admin.page_list.common.name_arabic_privacy_policy.input=//input[@id='Name(Arabic)']
admin.page_list.common.name_tamil.input=//input[@id='Name(Tamil):']
admin.page_list.common.name_english.input=//input[@id='Name(English):']
admin.page_list.common.description_english.editor=(//div[@contenteditable='true']//p)[1]
admin.page_list.common.description_arabic.editor=(//div[@contenteditable='true']//p)[2]
admin.page_list.common.description_tamil.editor=(//div[@contenteditable='true']//p)[3]
admin.page_list.common.faq.add.button=//button[normalize-space()='Add FAQ']
admin.page_list.common.faq.title.input=//input[@id='Tittle:']
admin.page_list.common.faq.description.textarea=//textarea[@placeholder='Enter Description']
web.global.action.submit.button=//button[normalize-space()='Submit']
web.global.action.cancel.button=//button[normalize-space()='Cancel']
web.global.action.delete.button=//button[normalize-space()='Delete']
web.global.action.yes.button=//button[normalize-space()='Yes']

