#app_settings_home_page_slider
admin.app_settings=//h2[@id='App Setting']
admin.app_settings.home_page_slider=//span[@id='Home page slider']
admin.app_settings.home_page_slider.add=//button[@class='buttonWidget']
admin.app_settings.home_page_slider.select_service=//span[@aria-label='select']
admin.app_settings.home_page_slider.select_taxi=//span[normalize-space()='Taxi Ride']
admin.app_settings.home_page_slider.upload_image=//input[@type='file']
admin.app_settings.home_page_slider.toggle=//div[@class='w-12 h-6 rounded-full transition-colors bg-red-500 peer-checked:bg-green-500']
admin.app_settings.home_page_slider.submit=//button[normalize-space()='Submit']
admin.app_settings.home_page_slider.close=//button[normalize-space()='Close']
admin.app_settings.home_page_slider.wrong_icon=//span[@id='closespan']
admin.app_settings.home_page_slider.gride_search_no=//input[@aria-label='No Filter Input']
admin.app_settings.home_page_slider.gride_search_slider_image=//input[@aria-label='Image Filter Input']
admin.app_settings.home_page_slider.gride_search_Slider_service_name=//input[@aria-label='Service Name Filter Input']
admin.app_settings.home_page_slider.edit_icon=//i[contains(@class, 'bi-pencil-square')]
admin.app.settings.home_page_slider.edit_select_service=//li[@id='Select Service:_2']
admin.app_settings.home_page_slider.edit_select=//span[@aria-label='Auto Ride']
admin.app_settings.home_page_slider.edit_select_image_upload=//img[@alt='Uploaded']
admin.app_settings.home_page_slider.banner_remove=//div[@class='absolute top-2 right-2 flex gap-2 opacity-0 group-hover:opacity-100 transition']
admin.app_settings.home_page_slider.delete_icon=//i[contains(@class, 'bi-trash') and contains(@class, 'Delete')]
admin.app_settings.home_page_slider.delete_yes=//button[normalize-space()='Yes, delete it!']
admin.app_settings.home_page_slider.delete_yes_ok_button=//button[normalize-space()='OK']

#advertisement_banner
admin.setting.advertisement_banner.sidebar_menu=//span[@id='Advertisement banner']
admin.setting.advertisement_banner.heading=//div[normalize-space()='Advertisement Banner']
admin.setting.advertisement_banner.add_banner=//button[@class='buttonWidget']
admin.setting.advertisement_banner.banner_url=//input[@id='Banner Url:']
admin.setting.advertisement_banner.upload_image=//input[@type='file' and @accept='image/*']
admin.setting.advertisement_banner.submit_btn=//button[normalize-space()='Submit']
admin.setting.advertisement_banner.url_grid_search=//input[@aria-label='Banner_Url Filter Input']
admin.setting.advertisement_edit_remove_image=//i[contains(@class, 'bi-x-lg')]
admin.setting.advertisement_edit_banner_button=//img[@alt='Uploaded']
admin.setting.advertisement.active_button=//i[contains(@class, 'Modify')]
admin.setting.advertisement.inactive_button=//i[contains(@class, 'Modify')]
admin.setting.advertisement_banner.delete_btn=//i[@class='bi bi-trash cursor-pointer gridIcon Delete']
admin.setting.advertisement_banner.confirm_delete_btn=//button[normalize-space()='Yes, delete it!']

#source_overview
admin.setting.source_overview=//span[@id="Source Overview"]
admin.setting.source_overview.add_button=//button[@class='buttonWidget']
admin.setting.source_overview.provider_type=//span[@aria-label='Select Provider Type']
admin.setting.source_overview.provider_type_customer=//span[normalize-space()='Customer']
admin.setting.source_overview.provider_type_driver=//li[@id='Provider Type_2']
admin.setting.source_overview.source_field=//input[@id='Source Name']
admin.setting.source_overview.provider_type_gride_search=//input[@aria-label='Provider Type Filter Input']
admin.setting.source_overview.source_filter_input=//input[@aria-label='Source Name Filter Input']
admin.setting.source_overview.customer=//span[@aria-label='Customer']
admin.setting.source_overview.driver=//span[@aria-label='Driver']
admin.app_settings.source_overview.delete_icon=//i[contains(@class, 'bi-trash') and contains(@class, 'Delete')]
admin.app_settings.source_overview.delete_yes=//button[normalize-space()='Yes, delete it!']

#Agreement Config
admin.app_settings.agreement_config.side_bar_menu=//span[@id='Agreement Config']
admin.app_settings.agreement_config.heading=//div[normalize-space()='Agreement Configuration']
admin.app_settings.agreement_config.add_agreement_heading.btn=//button[normalize-space()='Add Agreement Heading']
admin.app_settings.agreement_config.add_agreement.btn=//button[normalize-space()='Add Agreement']
admin.app_settings.agreement_config.add_agreement_heading.dropdown=//div[@id='Add Agreement Heading']//div[@role='button']
admin.app_settings.agreement_config.add_agreement_heading.dropdown_option=//li[@id='Add Agreement Heading_0']
admin.app_settings.agreement_config.add_subtitle.input=//input[@id='Add Subtitle']
admin.app_settings.agreement_config.add_description.input=//input[@id='Add Description']
admin.app_settings.agreement_config.form_submit.button=//button[normalize-space()='Submit']
admin.app_settings.agreement_config.subheading_search.field=//input[@aria-label='Subheading Filter Input']
admin.app_settings.agreement_config.edit_button=//i[@class='bi bi-pencil-square cursor-pointer gridIcon Navigate']
admin.app_settings.agreement_config.back_button=//button[@class='buttonWidget']
admin.app_settings.agreement_config.delete_button=//i[@class='bi bi-trash cursor-pointer gridIcon Delete']
admin.app_settings.agreement_config.confirm_delete_button=//button[normalize-space()='Yes, delete it!']


