# Main Module Entry Dashboard Landing Points
admin.provider.side_bar.menu_card=//h2[@id='Provider']
admin.provider.transport_provider_list.side_menu=//span[@id='Transport Providers List']


# Provider List dropdown Menu
admin.provider.service_type.drop_down=//div[@id="Select a Service Type"]
admin.provider.service_type.drop_down.option_taxi_ride=//li[@role='option' and @aria-label='Taxi Ride']
admin.provider.service_type.drop_down.option_bike_ride=//li[@role='option' and @aria-label='Bike Ride']
admin.provider.service_type.drop_down.option_auto_ride=//li[@role='option' and @aria-label='Auto Ride']
admin.provider.transport_provider_list.search_btn=//button[normalize-space()='Search']
admin.provider.transport_provider_list.clear_btn=//button[normalize-space()='Clear']

# Provider List Pagination And Download Button
admin.provider.transport_provider_list.grid_next_page=//span[@class='ag-icon ag-icon-next']
admin.provider.transport_provider_list.grid_previous_page=//span[@class='ag-icon ag-icon-previous']
admin.provider.transport_provider_list.grid_last_page=//span[@class='ag-icon ag-icon-last']
admin.provider.transport_provider_list.grid_first_page=//span[@class='ag-icon ag-icon-first']
admin.provider.transport_provider_list.download_btn=//button[@id='downlode-btn-id']
admin.provider.transport_provider_list.pdf_download_btn=//button[@id='pdf-btn-id']
admin.provider.transport_provider_list.excel_download_btn=//button[@id='excel-btn-id']
